name: Deploy to Minikube using GitHub Actions

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build Node.js Docker Image and Deploy to Minikube
    steps:
      - name: Checkout код репозитория
        uses: actions/checkout@v2

      - name: Start Minikube
        uses: medyagh/setup-minikube@master
        with:
          driver: docker

      - name: Проверяем кластер Kubernetes
        run: kubectl get pods -A

      - name: Build Docker image
        run: |
          eval $(minikube -p minikube docker-env)
          docker build --no-cache -t devopshint/node-app:latest .
          docker images

      - name: Проверяем, что образ есть в Minikube
        run: |
          eval $(minikube docker-env)
          docker images | grep node-app || echo "Образ не найден!"

      - name: Deploy to Minikube
        run: kubectl apply -f k8s-node-app.yaml

      - name: Проверяем поды перед тестами
        run: kubectl get pods -A

      - name: Проверяем логи подов
        run: kubectl logs -l app=nodejs-app || echo "No logs yet"

      - name: Debug pod issues
        run: kubectl describe pod -l app=nodejs-app

      - name: Ждём 10 секунд перед тестами (даём сервису запуститься)
        run: sleep 10

      - name: Test service URLs
        run: |
          minikube service list
          minikube service nodejs-app --url || echo "Service not available"
